server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/threat?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  freemarker:
    suffix: .ftl